
stages:
  # Stage 1: Data Ingestion
  data_ingestion:
    cmd: python -c "from src.components.data_ingestion import DataIngestion; di = DataIngestion(); di.initiate_data_ingestion()"
    deps:
      - src/components/data_ingestion.py
    params:
      - data_ingestion.ticker
      - data_ingestion.period
    outs:
      - artifacts/raw_stock_data.csv:
          cache: true
          persist: false
      - artifacts/train_stock_data.csv:
          cache: true
      - artifacts/test_stock_data.csv:
          cache: true

  # Stage 2: Data Transformation
  data_transformation:
    cmd: python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - artifacts/raw_stock_data.csv
    params:
      - data_transformation.sequence_length
      - data_transformation.test_split
    outs:
      - artifacts/processed_train.npy:
          cache: true
      - artifacts/processed_test.npy:
          cache: true
      - artifacts/scaler.pkl:
          cache: true

  # Stage 3: Model Training
  model_trainer:
    cmd: python -m src.components.model_trainer
    deps:
      - src/components/model_trainer.py
      - artifacts/processed_train.npy
      - artifacts/processed_test.npy
    params:
      - model.epochs
      - model.batch_size
      - model.learning_rate
      - model.lstm_units
    outs:
      - artifacts/stock_lstm_model.h5:
          cache: true

  # Stage 4: Model Evaluation
  model_evaluation:
    cmd: python -m mlops.evaluate_model
    deps:
      - mlops/evaluate_model.py
      - artifacts/stock_lstm_model.h5
      - artifacts/processed_test.npy
      - artifacts/scaler.pkl
    outs:
      - artifacts/evaluation_metrics.json:
          cache: false
      - artifacts/predictions_plot.png:
          cache: false
      - artifacts/error_distribution.png:
          cache: false

  # Stage 5: Model Registration
  model_registration:
    cmd: python -m mlops.registry
    deps:
      - mlops/registry.py
      - artifacts/stock_lstm_model.h5
      - artifacts/evaluation_metrics.json
    outs:
      - mlops/model_registry/:
          cache: true
          persist: true
